services:
  mya:
    image: mariadb:5.5.64
    hostname: mya
    container_name: mya
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: archive
      MYSQL_USER: myapi
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mya/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d