name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'VERSION'
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit:
    uses: jeffersonlab/java-workflows/.github/workflows/unit-ci.yml@v1
  integration:
    needs:
      - unit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Start containers
        run: docker compose -f "build.yaml" up -d
      - name: Wait for containers to settle
        run: docker exec -i myquery bash -c "sleep 10"
      - name: Run build and integration test
        run: ./gradlew integrationTest
      - name: Dump myquery logs
        if: always()
        run: docker logs myquery
      - name: Stop containers
        if: always()
        run: docker compose -f "build.yaml" down
