name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - name: Start containers
        run: docker compose -f "build.yaml" up -d
      - name: Wait for containers to settle
        run: docker exec -i myquery bash -c "sleep 10"
      - name: Run build and integration test
        run: ./gradlew integrationTest
      - name: Dump myquery logs
        if: always()
        run: docker logs myquery
      - name: Stop containers
        if: always()
        run: docker compose -f "build.yaml" down
